name: CI

on:
  push:
  pull_request:

defaults:
  run:
    working-directory: lab4/lab4_tests_example

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install deps (si las hay)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Debug layout (opcional)
        run: |
          pwd
          ls -la
          echo "---- src ----"
          ls -la src || true
          echo "---- tests ----"
          ls -la tests || true

      - name: Run unit tests
        run: |
          export PYTHONPATH=.
          python -m unittest discover -v
